# オブジェクト指向の活用

### 【前準備】

### 【問題1】これまで利用してきたクラスの列挙

・Pandas

df = heacet_all.describe()

・matplotlib

graf = plt.plot()

・scikit-learn

label = neigh.predict()

### 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

・メソッド

pd.read_csv()
np.array()
np.fix()
np.ones()
np.zeros()
np.full()

・インスタンス

### 【問題3】標準化クラスをスクラッチで作成

In [28]:
class ScratchStandardScaler(): #()は親クラスを継承する目的で、なくてもよい
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def __init__(self):   # コンストラクタ(初期化メソッド)
        self.mean_ = []   #平均値が入る
        self.var_ = []   #分散が入る

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        n = len(X[:,0])
        for i in range(X.shape[1]):
            mean_i = X[:,i].mean()
            self.mean_.append(mean_i)


        for k in range(X.shape[1]):
            ver_k = (np.sum((X[:,k]-self.mean_[k])**2)) / n
            self.var_.append(ver_k)
            pass
            return var_nd


    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量

        """
        μ = np.sqrt(var_nd)
        X_scaled = (X-mean_nd)/μ

        pass
        return X_scaled
    
# #-----------理解を助ける（i=0の場合）-------------
# n = len(X[:,0])
# print(n) #10
# print(X[0,0]) #5.1
# print(mean_nd[0]) #4.859999999999999
# print(X[:,0]-mean_nd[0]) #[ 0.24  0.04 -0.16 -0.26  0.14  0.54 -0.26  0.14 -0.46  0.04]　引き算だけどリストで出力
# print((X[:,0]-mean_nd[0])**2) #[0.0576 0.0016 0.0256 0.0676 0.0196 0.2916 0.0676 0.0196 0.2116 0.0016]
# print((np.sum((X[:,0]-mean_nd[0])**2))/n)
# print(X.shape[1]) #4

# #-----------作成過程のメモ-------------
# import numpy as np
# import math
# from sklearn.datasets import load_iris
# data = load_iris()
# X = data.data[:10]
# display(X)

# print("------def fit(self, X):-------") 
# mean_nd = []
# n = len(X[:,0])
# for i in range(X.shape[1]):
#     mean_i = X[:,i].mean()
#     mean_nd.append(mean_i)
    
# print(mean_nd)

# print("------transform(self, X)-------") 
# var_nd = []
# for k in range(X.shape[1]):
#     ver_k = (np.sum((X[:,k]-mean_nd[k])**2))/n
#     var_nd.append(ver_k)
# print(var_nd)
# print("------検証中1---------") 
# #np.sqrt(a)でaの平方根を取る
# μ = np.sqrt(var_nd)
# print(μ)
# print("------検証中2---------") 
# print((X-mean_nd)/μ)



In [27]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.859999999999999, 3.31, 1.45, 0.22000000000000003]
分散 : [0.07640000000000002]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


### 【問題4】 四則演算を行うクラスの作成

In [57]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value): #コンストラクタ(コンストラクタはreturnしちゃだめ)
        self.value = value
        
        #if type(self.value) != int and type(self.value) != float:
        #if not (type(value) in (int, float)):
        if type(value) in (int, float):
            
            print("初期値{}が設定されました".format(self.value))
            
        else:
            self.value = None
            
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    
    def sub(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2
        
    def mul(self, value2):
        """
        受け取った引数をself.valueに掛ける
        """
        self.value *= value2
        
    def div(self, value2):
        """
        受け取った引数でself.valueを割る
        """
        self.value /= value2
        
example = ExampleClass(X_std)
print(type(example))
if example.value is None:
    print('Error!')
    
else:
    print("value : {}".format(example.value))
    example.mul(3)
    print("value : {}".format(example.value))

<class '__main__.ExampleClass'>
Error!
